def display_normativa_details(self):
    print("ID: ", self.id_normativa)
    print("Tipo de Normativa: ", self.tipo_normativa)
    print("Número de Normativa: ", self.nro_normativa)
    print("Fecha: ", self.fecha)
    print("Nombre: ", self.nombre)
    print("Descripción: ", self.descripcion)
    print("Categoría: ", self.categoria)
    print("Jurisdicción: ", self.jurisdiccion)
    print("Órgano Legislativo: ", self.organo_legislativo)
    print("Palabras Clave: ", self.palabras_clave)
    print("-" * 110)
